schema {
    query: Query
    mutation: Mutation
}

enum LanguageName {
    English
    Spanish
    French
    German
    Russian
    Ukrainian
}

enum StoryType {
    BedtimeStory
    Adventure
    SciFi
    Fantasy
    Pirates
    Superheroes
    Animals
    FairyTales
}

type User {
    userId: ID!
    username: String!
    email: String!
    createdAt: AWSDateTime!
    stories: [Story!]
}

type Placeholder {
    name: String!
    text: String!
}

type Chapter {
    chapterId: ID!
    storyId: ID!
    content: String!
    template: String!
    placeholders: [Placeholder!]!
    createdAt: AWSDateTime!
}

type Story {
    storyId: ID!
    userId: ID!
    targetLanguage: LanguageName!
    explainLanguage: LanguageName!
    storyType: StoryType!
    startedAt: AWSDateTime!
    title: String!
    chapters: [Chapter!]!
}

input StartStoryArguments {
    userId: ID!
    clientRequestId: ID!
    targetLanguage: LanguageName!
    explainLanguage: LanguageName!
    storyType: StoryType!
}

#input SolveTemplateArguments {
#    userId: ID!
#    clientRequestId: ID!
#    storyId: ID!
#    chapterId: ID!
#    placeholders: [Placeholder!]!
#}

type Mutation {
    startStory(args: StartStoryArguments!): Story!
    #solveTemplate(args: SolveQuizArguments!): QuizResult!
}

type Query {
    listStories(userId: ID!): [Story!]!
}
