schema {
    query: Query
    mutation: Mutation
}

enum LanguageName {
    English
    Spanish
    French
    German
    Russian
    Ukrainian
}

enum StoryType {
    BedtimeStory
    Adventure
    SciFi
    Fantasy
    Pirates
    Superheroes
    Animals
    FairyTales
}

type User {
    userId: ID!
    username: String!
    email: String!
    createdAt: AWSDateTime!
    stories: [Story!]
}

type Placeholder {
    name: String!
    text: String!
}

type UserInputValue {
    name: String!
    text: String!
}

enum ChapterStatus {
    Created
    VerifiedNoMistakes
    VerifiedWithMistakes
    Completed
}

type Chapter {
    chapterId: ID!
    storyId: ID!
    content: String!
    template: String!
    placeholders: [Placeholder!]!
    userInput: [UserInputValue!]!    
    createdAt: AWSDateTime!
    completedAt: AWSDateTime
    status: ChapterStatus!
    finalizedContent: String
}

type Story {
    storyId: ID!
    userId: ID!
    targetLanguage: LanguageName!
    explainLanguage: LanguageName!
    storyType: StoryType!
    startedAt: AWSDateTime!
    title: String!
    chapters: [Chapter!]!
}

# start story

input StartStoryInput {
    userId: ID!
    clientRequestId: ID!
    targetLanguage: LanguageName!
    explainLanguage: LanguageName!
    storyType: StoryType!
}

type StartStoryError {
    message: String!
}

type StartStoryPayload {
    errors: [StartStoryError!]!
    story: Story
}

# check template

input UserInputValueInput {
    name: String!
    text: String!
}

input CheckTemplateInput {
    userId: ID!
    clientRequestId: ID!
    targetLanguage: LanguageName!
    explainLanguage: LanguageName!    
    storyId: ID!
    chapterId: ID!
    placeholders: [UserInputValueInput!]!
}

type CheckTemplateError {
    message: String!
}

type CheckTemplatePayload {
    errors: [CheckTemplateError!]!
    mistakes: [MistakeExplanation!]!
    chapter: Chapter
}

type MistakeExplanation {
    placeholder: Placeholder!
    explanation: String!
    hint: String!
}

type Mutation {
    startStory(input: StartStoryInput!): StartStoryPayload! @aws_cognito_user_pools
    checkTemplate(input: CheckTemplateInput!): CheckTemplatePayload! @aws_cognito_user_pools
}

type Query {
    listStories(userId: ID!): [Story!]! @aws_cognito_user_pools
    fetchStoryById(userId: ID!, storyId: ID!): Story @aws_cognito_user_pools
}
